spring:
  kafka:
    consumer:
      group-id: ${CONSUMER_GROUP_ID:#{T(java.util.UUID).randomUUID().toString()}}
    bootstrap-servers: broker:9092
  ssl:
    bundle:
      jks:
        server-ssl-bundle:
          key:
            alias: "server"
          keystore:
            location: "/certs/keystore.p12"
            password: "changeme"
            type: "PKCS12"
          truststore:
            location: "/certs/truststore.p12"
            password: "changeme"
            type: "PKCS12"
server:
  ssl:
    enabled: false
  port: 8080
logging:
  level:
    org:
      apache:
        kafka: error
springdoc:
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - loggers
