#spring:
#  kafka:
#    bootstrap-servers: localhost:9999
#    consumer:
#      bootstrap-servers: localhost:9999
#      group-id: consumer-group
    #    producer:
#      bootstrap-servers: localhost:9999
#    streams:
#      bootstrap-servers: localhost:9999
logging:
  level:
    org.apache.kafka: INFO