spring:
  kafka:
#    bootstrap-servers: localhost:9999
    consumer:
#      bootstrap-servers: localhost:9999
      group-id: kafka-messaging-example
#    producer:
#      bootstrap-servers: localhost:9999
#    streams:
#      bootstrap-servers: localhost:9999
    admin:
      auto-create: true