spring:
  kafka:
    consumer:
      group-id: ${CONSUMER_GROUP_ID:#{T(java.util.UUID).randomUUID().toString()}}
    bootstrap-servers: localhost:9092
  ssl:
    bundle:
      jks:
        server-ssl-bundle:
          key:
            alias: "myalias"
          keystore:
            location: "classpath:unified.p12"
            password: "changeme"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.p12"
            password: "changeme"
            type: "PKCS12"
server:
  ssl:
    bundle: "server-ssl-bundle"
    client-auth: need
    enabled: true
jwt:
  secret: "U29tZTFDcmF6eTJTZWNyZXQzU3RyaW5nNA=="
logging:
  level:
    org.apache.kafka: error
    org.springframework.security: DEBUG
