spring:
  kafka:
    consumer:
      group-id: ${CONSUMER_GROUP_ID:#{T(java.util.UUID).randomUUID().toString()}}
    bootstrap-servers: broker:9092
  ssl:
    bundle:
      jks:
        server-ssl-bundle:
          key:
            alias: "myalias"
          keystore:
            location: "classpath:keystore.p12"
            password: "changeme"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.p12"
            password: "changeme"
            type: "PKCS12"
server:
  ssl:
    enabled: false
logging:
  level:
    org.apache.kafka: error
    org.springframework.security: debug
springdoc:
  show-actuator: true
