tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/server.crt
        keyFile: /certs/server.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
      clientAuth:
        caFiles:
          - certs/trust.crt
        clientAuthType: RequireAndVerifyClientCert
