tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
      clientAuth:
        caFiles:
          - /certs/ca.pem
        clientAuthType: RequireAndVerifyClientCert
#        clientAuthType: NoClientCert
#        clientAuthType: RequestClientCert
#        clientAuthType: RequireAnyClientCert
