services:
  traefik:
    image: traefik:v2.11
    container_name: proxy_traefik
    networks:
      - kafka_messaging_example
    ports:
      - "8443:8080"
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/steve/IdeaProjects/kafka-messaging-example/project-resources/traefik/traefik-dynamic-config.yml:/etc/traefik/dynamic/traefik-dynamic-config.yml:ro
      - /home/steve/Downloads/server.crt:/certs/cert.pem:ro
      - /home/steve/Downloads/server.key:/certs/key.pem:ro
      - /home/steve/Downloads/ca.crt:/certs/ca.pem:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=HostRegexp(`{host:.+}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"
      - "traefik.http.routers.dashboard.service=api@internal"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.websecure.address=:8443"
      - "--entrypoints.dashboard.address=:8888"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=kafka_messaging_example"
      - "--providers.file.directory=/etc/traefik/dynamic"

  redpanda_broker:
    image: redpandadata/redpanda:v23.3.8
    container_name: broker
    networks:
      - kafka_messaging_example
    volumes:
      - broker:/var/lib/redpanda/data:rw
    cap_add:
      - SYS_NICE
    labels:
      - "traefik.enable=false"
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://broker:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://broker:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr broker:33145
      - --advertise-rpc-addr broker:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=warn
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  example_app:
    image: docker.io/library/kafka-messaging-example:latest
    container_name: example_app
    networks:
      - kafka_messaging_example
    environment:
      - THC_PATH=/actuator/health
      - THC_PORT=8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example-app.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.example-app.entrypoints=websecure"
      - "traefik.http.routers.example-app.tls=true"
      - "traefik.http.routers.example-app.tls.options=default"
      - "traefik.http.routers.example-app.service=example-app"
      - "traefik.http.middlewares.example-app-pass-pem.passtlsclientcert.pem=true"
      - "traefik.http.routers.example-app.middlewares.example-app-pass-pem@docker"
      - "traefik.http.services.example-app.loadbalancer.server.port=8080"
    healthcheck:
      test: [ "CMD", "/cnb/process/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      redpanda_broker:
        condition: service_healthy

networks:
  kafka_messaging_example:
    name: kafka_messaging_example
    driver: bridge

volumes:
  broker: null